insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 1,'Eula','Lane','eula.lane@jigrormo.ye','(762) 526-5961','1954-01-30','Insurance Clerk','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 2,'Barry','Rodriquez','barry.rodriquez@zun.mm','(267) 955-5124','2013-01-30','Mortarman','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 3,'Eugenia','Selvi','eugenia.selvi@capfad.vn','(680) 368-2192','1973-01-15','Beer Coil Cleaner','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 4,'Alejandro','Miles','alejandro.miles@dec.bn','(281) 301-2039','2013-03-04','Scale Attendant','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 5,'Cora','Tesi','cora.tesi@bivo.yt','(600) 616-7955','1971-05-02','Clinical Audiologist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 6,'Marguerite','Ishii','marguerite.ishii@judbilo.gn','(882) 813-1374','1937-01-27','Parking Meter Collector','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 7,'Mildred','Jacobs','mildred.jacobs@joraf.wf','(642) 665-1763','1966-09-01','Business Unit Manager','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 8,'Gene','Goodman','gene.goodman@kem.tl','(383) 458-2132','2009-07-12','Technical Communicator','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 9,'Lettie','Bennett','lettie.bennett@odeter.bb','(769) 335-6771','1958-09-16','Correctional Officer Sergeant','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 10,'Mabel','Leach','mabel.leach@lisohuje.vi','(803) 586-8035','1945-08-23','Food Chemist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 11,'Jordan','Miccinesi','jordan.miccinesi@duod.gy','(531) 919-2280','1981-10-04','Signals Intelligence/Electronic Warfare Chief','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 12,'Marie','Parkes','marie.parkes@nowufpus.ph','(814) 667-8937','1942-08-05','Language Pathologist','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 13,'Rose','Gray','rose.gray@kagu.hr','(713) 311-8766','1957-08-04','Wildlife Officer','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 14,'Garrett','Stokes','garrett.stokes@fef.bg','(381) 421-2371','2008-05-15','Bindery Machine Operator','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 15,'Barbara','Matthieu','barbara.matthieu@derwogi.jm','(940) 463-7299','1929-05-11','Instructional Aide','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 16,'Jean','Rhodes','jean.rhodes@wehovuce.gu','(777) 435-9570','1948-10-18','Clinical Psychiatrist','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 17,'Jack','Romoli','jack.romoli@zamum.bw','(517) 393-9630','1974-08-14','Mortician Investigator','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 18,'Pearl','Holden','pearl.holden@dunebuh.cr','(711) 904-3669','1948-12-09','Rod Buster Helper','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 19,'Belle','Montero','belle.montero@repiwid.si','(935) 404-4792','1932-01-02','Classroom Aide','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 20,'Olive','Molina','olive.molina@razuppa.ga','(935) 267-8492','1933-07-14','Traditional Chinese Herbalist','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 21,'Minerva','Todd','minerva.todd@kulmenim.ad','(763) 948-4815','1949-12-15','Electronic Drafter','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 22,'Bobby','Pearson','bobby.pearson@ib.kg','(238) 240-2561','2014-05-09','Vault Teller','Worker',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 23,'Larry','Ciappi','larry.ciappi@ba.lk','(410) 257-1723','1995-05-25','Fire Sprinkler Installer','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 24,'Ronnie','Salucci','ronnie.salucci@tohhij.lv','(566) 726-3346','1973-11-26','Brewery Pumper','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 25,'Walter','Grossi','walter.grossi@tuvo.sa','(416) 906-7221','1987-01-14','Kitchen Chef','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 26,'Frances','Koopmans','frances.koopmans@foga.tw','(611) 712-1562','1966-03-07','Medical Esthetician','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 27,'Frances','Fujimoto','frances.fujimoto@uswuzzub.jp','(919) 887-8542','1935-08-11','Auto Tire Worker','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 28,'Olivia','Vidal','olivia.vidal@hivwerip.vc','(982) 684-7650','1932-11-18','Semi-Truck Driver','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 29,'Edna','Henry','edna.henry@gugusu.rw','(811) 931-8202','1946-10-02','Command And Control','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 30,'Lydia','Brun','lydia.brun@zedekak.md','(927) 400-3928','1928-11-14','Drywall Hanger','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 31,'Jay','Blake','jay.blake@ral.mk','(365) 345-1498','2008-12-02','Real Property Evaluator','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 32,'Isabel','Serafini','isabel.serafini@turuhu.bh','(656) 968-9869','1972-12-10','Human Performance Professor','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 33,'Rebecca','Carter','rebecca.carter@omjo.et','(739) 612-6585','1958-06-29','V/Stol Landing Signal Officer','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 34,'Maurice','Fabbrini','maurice.fabbrini@rig.bh','(485) 521-2687','1992-05-04','Air Control/Anti-Air Warfare Officer','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 35,'Ollie','Turnbull','ollie.turnbull@sicewap.org','(835) 620-3330','1943-12-30','General Superintendent','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 36,'Jerry','Hopkins','jerry.hopkins@fo.mh','(211) 851-5960','2014-01-23','Child Protective Services Social Worker','External',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 37,'Nora','Lyons','nora.lyons@gegijap.na','(811) 311-5257','1944-11-06','Lens Grinder and Polisher','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 38,'Anne','Weiß','anne.weiß@kuvesa.pe','(843) 836-3759','1940-05-25','Civil Engineering Professor','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 39,'Louise','Gauthier','louise.gauthier@lapahu.mt','(913) 235-1856','1929-09-04','Mobile Home Servicer','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 40,'Lloyd','Fani','lloyd.fani@zev.ru','(467) 487-7239','1991-08-09','Floor Refinisher','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 41,'Maud','Dunn','maud.dunn@nabeaga.ni','(724) 340-3634','1954-10-31','Senior Sales Associate','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 42,'Henry','Gigli','henry.gigli@kaot.ps','(413) 229-8428','1988-01-03','Tile Designer','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 43,'Virgie','Werner','virgie.werner@tawuctuj.cf','(886) 292-9749','1941-02-11','Econometrics Professor','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 44,'Gregory','Cozzi','gregory.cozzi@eh.ru','(418) 472-1239','1993-12-05','Basketball Player','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 45,'Lucinda','Gil','lucinda.gil@fajjusuz.kr','(961) 233-3461','1933-11-26','Indirect Fire Infantryman','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 46,'Gertrude','Verbeek','gertrude.verbeek@pave.cc','(605) 226-4037','1963-12-10','Licensed Esthetician','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 47,'Mattie','Graham','mattie.graham@ispaviw.gt','(719) 765-1705','1956-10-07','Antisubmarine Warfare Intelligence Officer','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 48,'Bryan','Shaw','bryan.shaw@ha.ee','(232) 228-5539','2018-06-03','Research Assistant','Manager',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 49,'Essie','Adams','essie.adams@iliat.cw','(768) 554-8377','1957-12-13','Cigar Roller','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 50,'Gary','Osborne','gary.osborne@do.ga','(311) 731-7079','2008-10-01','Customer Support Representative','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 51,'Richard','Silva','richard.silva@wi.lc','(207) 554-6244','2014-05-13','Programmer','Manager',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 52,'Dustin','Pestelli','dustin.pestelli@iwage.la','(558) 913-2855','1977-09-16','Global Engineering Manager','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 53,'Henrietta','Hilton','henrietta.hilton@joopoju.pn','(832) 759-6654','1943-07-11','Telegraph and Teletype Operator','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 54,'Francisco','Giordano','francisco.giordano@gojawu.tn','(482) 736-8079','1987-12-18','Hairpiece Stylist','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 55,'Cynthia','Sardi','cynthia.sardi@afigoh.mm','(677) 345-2680','1973-06-07','Tobacco Buyer','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 56,'Lula','Testi','lula.testi@benom.tj','(610) 374-7581','1971-04-04','Marine Steamfitter','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 57,'Bess','Lucas','bess.lucas@jevakbe.cd','(982) 583-8067','1928-09-12','Attending Anesthesiologist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 58,'Linnie','Driessen','linnie.driessen@darhow.tr','(680) 266-3167','1967-06-13','Certified Indoor Environmentalist','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 59,'Eva','Tesi','eva.tesi@dupid.cf','(611) 955-4652','1971-04-25','Land Management Forester','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 60,'Augusta','Sakai','augusta.sakai@comouc.ee','(940) 714-8088','1936-01-31','Digital Proofing and Platemaker','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 61,'Mathilda','Schwarz','mathilda.schwarz@igunisi.ao','(868) 481-5125','1941-05-26','Public Health Veterinarian','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 62,'Joe','Riley','joe.riley@pe.vu','(225) 395-2772','2016-11-03','Statement Processor','External',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 63,'Leon','McGee','leon.mcgee@puk.se','(365) 837-6888','2010-08-20','Computer Applications Developer','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 64,'Florence','Viviani','florence.viviani@vegub.no','(606) 352-8734','1969-06-12','African History Professor','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 65,'Lee','Miceli','lee.miceli@rucwi.pf','(555) 800-7339','1981-09-15','Gastroenterology Professor','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 66,'Celia','Sodi','celia.sodi@agijit.iq','(657) 357-3671','1972-07-08','Laboratory Animal Caretaker','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 67,'Aaron','Misuri','aaron.misuri@loolu.lu','(523) 789-5485','1981-06-09','Water Pump Installer','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 68,'Fanny','Parkinson','fanny.parkinson@tupwovali.cw','(766) 966-7387','1949-03-21','Orthopedic Cast Specialist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 69,'Phoebe','Vitale','phoebe.vitale@hidge.fo','(672) 613-2954','1969-07-22','Budget Coordinator','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 70,'Edith','Brennan','edith.brennan@liowci.ir','(803) 549-9387','1948-01-01','Railroad Engineer','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 71,'Jeremy','Marilli','jeremy.marilli@vesa.pf','(526) 435-1819','1983-07-06','Chief Projectionist','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 72,'Kathryn','Huet','kathryn.huet@wupikdoh.by','(937) 855-5936','1926-12-23','Telecasting Engineer','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 73,'Lelia','Matsuo','lelia.matsuo@dajsiphaj.az','(960) 335-6192','1935-01-03','Drama Therapist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 74,'Virginia','Woods','virginia.woods@soofpe.ht','(735) 809-2611','1954-10-11','General Superintendent','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 75,'Sally','Aoki','sally.aoki@aruzusjas.tc','(857) 797-7918','1936-12-12','Technical Communicator','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 76,'Isabelle','de Ridder','isabelle.deridder@ufeco.in','(659) 331-1543','1962-09-28','Leisure Studies Professor','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 77,'Rosie','Murphy','rosie.murphy@uneehi.id','(759) 639-8597','1958-03-31','Air Conditioning Service Technician','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 78,'Lou','Meyer','lou.meyer@hahinaba.gm','(942) 352-4854','1928-12-24','Business Unit Manager','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 79,'Rodney','Love','rodney.love@zun.ph','(247) 867-8287','2012-04-19','Job Estimator','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 80,'Kenneth','Bianchini','kenneth.bianchini@jo.ws','(302) 793-9936','2001-04-11','Correctional Officer Sergeant','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 81,'Essie','Dietrich','essie.dietrich@goltuefo.mn','(861) 740-6628','1938-12-12','Parking Meter Collector','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 82,'Leila','Simon','leila.simon@lupuwuzo.gw','(953) 866-9992','1930-09-08','Signals Intelligence/Electronic Warfare Chief','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 83,'Eva','Pierre','eva.pierre@reduzris.ee','(915) 491-8384','1927-09-20','Clinical Psychiatrist','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 84,'Landon','Moretti','landon.moretti@pubsav.sk','(584) 909-6235','1980-12-23','Wildlife Officer','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 85,'Mittie','Sardi','mittie.sardi@lullip.nf','(673) 849-4256','1973-06-02','Food Chemist','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 86,'Corey','McDaniel','corey.mcdaniel@aba.tc','(268) 208-9643','2012-08-06','Advanced Foreign Counterintelligence Specialist (Afcs)','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 87,'Hester','Stein','hester.stein@kettujwo.eu','(873) 489-6641','1939-05-30','Forest Fire Officer','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 88,'Danny','Lowe','danny.lowe@ju.sd','(243) 974-5539','2013-09-11','Catalogue Illustrator','External',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 89,'Lillie','Winter','lillie.winter@vioburez.vi','(816) 699-1291','1945-08-06','Knife Grinder','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 90,'Brandon','Borchi','brandon.borchi@ig.al','(319) 401-1090','2000-05-28','Neuropsychiatrist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 91,'Isaac','Bernardi','isaac.bernardi@omu.bj','(359) 691-6408','2001-11-08','Bottle Packer','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 92,'Clyde','Crawford','clyde.crawford@luw.dz','(273) 892-4646','2018-11-11','Special Education Kindergarten Teacher','External',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 93,'Paul','Sherman','paul.sherman@pi.cf','(304) 610-2881','2008-04-19','Commercial Art Instructor','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 94,'Craig','Russell','craig.russell@zu.nz','(237) 969-2900','2020-02-15','Ferryboat Captain','Supervisor',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 95,'John','Sutton','john.sutton@ag.ee','(207) 424-6468','2013-04-28','School Social Worker','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 96,'Francisco','Formigli','francisco.formigli@fopav.tn','(481) 661-8179','1990-04-12','Joint Terminal Attack Controller','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 97,'Gary','Baker','gary.baker@ji.cf','(212) 510-3444','2022-05-02','VP Sales','Worker',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 98,'Earl','Giovannoni','earl.giovannoni@lojet.ge','(433) 862-3076','1987-09-10','Auto Service Station Attendant','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 99,'Helen','Zanieri','helen.zanieri@ukve.tn','(619) 506-4452','1969-01-22','Healthcare Social Worker','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 100,'Agnes','Toccafondi','agnes.toccafondi@viipo.ae','(616) 688-6883','1971-02-11','Comedian','External',false)
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 1,'Eula Lane','Philippines','(762) 526-5961','eula.lane@jigrormo.ye','2016-09-20T14:35:35','jigrormo')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 2,'Barry Rodriquez','Bhutan','(267) 955-5124','barry.rodriquez@zun.mm','2022-08-15T00:00','zun')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 3,'Eugenia Selvi','Liechtenstein','(680) 368-2192','eugenia.selvi@capfad.vn','2018-08-13T10:25:25','capfad')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 4,'Alejandro Miles','Bhutan','(281) 301-2039','alejandro.miles@dec.bn','2022-08-19T17:43:43','dec')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 5,'Cora Tesi','Macedonia','(600) 616-7955','cora.tesi@bivo.yt','2018-06-12T06:16:16','bivo')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 6,'Marguerite Ishii','Syria','(882) 813-1374','marguerite.ishii@judbilo.gn','2015-01-07T15:39:39','judbilo')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 7,'Mildred Jacobs','Mexico','(642) 665-1763','mildred.jacobs@joraf.wf','2017-12-23T13:33:33','joraf')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 8,'Gene Goodman','Burkina Faso','(383) 458-2132','gene.goodman@kem.tl','2022-04-07T03:07:07','kem')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 9,'Lettie Bennett','Norfolk Island','(769) 335-6771','lettie.bennett@odeter.bb','2017-03-08T14:36:36','odeter')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 10,'Mabel Leach','Slovenia','(803) 586-8035','mabel.leach@lisohuje.vi','2015-11-16T21:53:53','lisohuje')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 11,'Jordan Miccinesi','Iran','(531) 919-2280','jordan.miccinesi@duod.gy','2019-06-28T05:13:13','duod')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 12,'Marie Parkes','Sri Lanka','(814) 667-8937','marie.parkes@nowufpus.ph','2015-07-28T01:04:04','nowufpus')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 13,'Rose Gray','Norway','(713) 311-8766','rose.gray@kagu.hr','2017-01-26T22:56:56','kagu')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 14,'Garrett Stokes','Cameroon','(381) 421-2371','garrett.stokes@fef.bg','2022-02-24T12:32:32','fef')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 15,'Barbara Matthieu','Ukraine','(940) 463-7299','barbara.matthieu@derwogi.jm','2014-04-01T10:25:25','derwogi')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 16,'Jean Rhodes','Saudi Arabia','(777) 435-9570','jean.rhodes@wehovuce.gu','2016-03-11T20:50:50','wehovuce')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 17,'Jack Romoli','Lebanon','(517) 393-9630','jack.romoli@zamum.bw','2018-10-10T05:14:14','zamum')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 18,'Pearl Holden','Saudi Arabia','(711) 904-3669','pearl.holden@dunebuh.cr','2016-03-16T00:02:02','dunebuh')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 19,'Belle Montero','Turkmenistan','(935) 404-4792','belle.montero@repiwid.si','2014-07-06T05:14:14','repiwid')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 20,'Olive Molina','Trinidad & Tobago','(935) 267-8492','olive.molina@razuppa.ga','2014-08-31T01:04:04','razuppa')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 21,'Minerva Todd','Samoa','(763) 948-4815','minerva.todd@kulmenim.ad','2016-04-22T01:02:02','kulmenim')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 22,'Bobby Pearson','Belize','(238) 240-2561','bobby.pearson@ib.kg','2022-10-01T07:19:19','ib')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 23,'Larry Ciappi','Equatorial Guinea','(410) 257-1723','larry.ciappi@ba.lk','2020-11-07T04:10:10','ba')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 24,'Ronnie Salucci','Liberia','(566) 726-3346','ronnie.salucci@tohhij.lv','2018-09-14T04:10:10','tohhij')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 25,'Walter Grossi','Guadeloupe','(416) 906-7221','walter.grossi@tuvo.sa','2020-01-07T12:30:30','tuvo')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 26,'Frances Koopmans','Micronesia','(611) 712-1562','frances.koopmans@foga.tw','2017-12-06T11:27:27','foga')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 27,'Frances Fujimoto','Tanzania','(919) 887-8542','frances.fujimoto@uswuzzub.jp','2014-11-15T02:06:06','uswuzzub')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 28,'Olivia Vidal','Tristan da Cunha','(982) 684-7650','olivia.vidal@hivwerip.vc','2014-08-07T15:38:38','hivwerip')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 29,'Edna Henry','Singapore','(811) 931-8202','edna.henry@gugusu.rw','2015-12-27T02:06:06','gugusu')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 30,'Lydia Brun','United Kingdom','(927) 400-3928','lydia.brun@zedekak.md','2014-03-14T07:17:17','zedekak')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 31,'Jay Blake','Cambodia','(365) 345-1498','jay.blake@ral.mk','2022-03-16T10:25:25','ral')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 32,'Isabel Serafini','Liechtenstein','(656) 968-9869','isabel.serafini@turuhu.bh','2018-08-10T09:24:24','turuhu')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 33,'Rebecca Carter','North Korea','(739) 612-6585','rebecca.carter@omjo.et','2017-02-28T01:02:02','omjo')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 34,'Maurice Fabbrini','France','(485) 521-2687','maurice.fabbrini@rig.bh','2020-07-18T11:29:29','rig')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 35,'Ollie Turnbull','South Georgia & South Sandwich Islands','(835) 620-3330','ollie.turnbull@sicewap.org','2015-09-17T00:01:01','sicewap')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 36,'Jerry Hopkins','Benin','(211) 851-5960','jerry.hopkins@fo.mh','2022-09-20T16:40:40','fo')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 37,'Nora Lyons','Somalia','(811) 311-5257','nora.lyons@gegijap.na','2015-10-18T18:46:46','gegijap')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 38,'Anne Weiß','St. Martin','(843) 836-3759','anne.weiß@kuvesa.pe','2015-05-09T17:43:43','kuvesa')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 39,'Louise Gauthier','Uganda','(913) 235-1856','louise.gauthier@lapahu.mt','2014-04-12T13:34:34','lapahu')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 40,'Lloyd Fani','French Polynesia','(467) 487-7239','lloyd.fani@zev.ru','2020-06-22T10:26:26','zev')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 41,'Maud Dunn','Paraguay','(724) 340-3634','maud.dunn@nabeaga.ni','2016-10-17T16:40:40','nabeaga')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 42,'Henry Gigli','Greenland','(413) 229-8428','henry.gigli@kaot.ps','2020-02-11T10:25:25','kaot')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 43,'Virgie Werner','St. Lucia','(886) 292-9749','virgie.werner@tawuctuj.cf','2015-06-04T17:42:42','tawuctuj')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 44,'Gregory Cozzi','Falkland Islands','(418) 472-1239','gregory.cozzi@eh.ru','2020-09-14T19:48:48','eh')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 45,'Lucinda Gil','Tonga','(961) 233-3461','lucinda.gil@fajjusuz.kr','2014-09-14T19:48:48','fajjusuz')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 46,'Gertrude Verbeek','Morocco','(605) 226-4037','gertrude.verbeek@pave.cc','2017-09-15T20:52:52','pave')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 47,'Mattie Graham','Pakistan','(719) 765-1705','mattie.graham@ispaviw.gt','2016-12-27T16:41:41','ispaviw')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 48,'Bryan Shaw','Ascension Island','(232) 228-5539','bryan.shaw@ha.ee','2023-02-26T03:07:07','ha')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 49,'Essie Adams','Northern Mariana Islands','(768) 554-8377','essie.adams@iliat.cw','2017-02-08T02:05:05','iliat')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 50,'Gary Osborne','Cambodia','(311) 731-7079','gary.osborne@do.ga','2022-03-10T14:36:36','do')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 51,'Richard Silva','Belize','(207) 554-6244','richard.silva@wi.lc','2022-10-01T07:18:18','wi')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 52,'Dustin Pestelli','Kazakhstan','(558) 913-2855','dustin.pestelli@iwage.la','2019-01-31T23:57:57','iwage')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 53,'Henrietta Hilton','South Korea','(832) 759-6654','henrietta.hilton@joopoju.pn','2015-08-31T07:19:19','joopoju')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 54,'Francisco Giordano','Greenland','(482) 736-8079','francisco.giordano@gojawu.tn','2020-02-09T00:02:02','gojawu')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 55,'Cynthia Sardi','Libya','(677) 345-2680','cynthia.sardi@afigoh.mm','2018-08-28T00:01:01','afigoh')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 56,'Lula Testi','Macedonia','(610) 374-7581','lula.testi@benom.tj','2018-06-09T02:07:07','benom')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 57,'Bess Lucas','United Kingdom','(982) 583-8067','bess.lucas@jevakbe.cd','2014-03-07T21:54:54','jevakbe')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 58,'Linnie Driessen','Mauritius','(680) 266-3167','linnie.driessen@darhow.tr','2018-01-21T02:06:06','darhow')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 59,'Eva Tesi','Macedonia','(611) 955-4652','eva.tesi@dupid.cf','2018-06-11T01:04:04','dupid')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 60,'Augusta Sakai','Tajikistan','(940) 714-8088','augusta.sakai@comouc.ee','2014-12-02T00:00','comouc')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 61,'Mathilda Schwarz','St. Kitts & Nevis','(868) 481-5125','mathilda.schwarz@igunisi.ao','2015-06-14T06:16:16','igunisi')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 62,'Joe Riley','Bahamas','(225) 395-2772','joe.riley@pe.vu','2022-12-31T01:02:02','pe')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 63,'Leon McGee','Brunei','(365) 837-6888','leon.mcgee@puk.se','2022-05-18T23:58:58','puk')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 64,'Florence Viviani','Mali','(606) 352-8734','florence.viviani@vegub.no','2018-04-04T03:07:07','vegub')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 65,'Lee Miceli','Iran','(555) 800-7339','lee.miceli@rucwi.pf','2019-06-26T10:25:25','rucwi')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 66,'Celia Sodi','Lithuania','(657) 357-3671','celia.sodi@agijit.iq','2018-07-25T12:30:30','agijit')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 67,'Aaron Misuri','Iran','(523) 789-5485','aaron.misuri@loolu.lu','2019-06-16T11:29:29','loolu')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 68,'Fanny Parkinson','São Tomé and Príncipe','(766) 966-7387','fanny.parkinson@tupwovali.cw','2016-03-26T23:57:57','tupwovali')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 69,'Phoebe Vitale','Mali','(672) 613-2954','phoebe.vitale@hidge.fo','2018-04-08T17:43:43','hidge')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 70,'Edith Brennan','Serbia','(803) 549-9387','edith.brennan@liowci.ir','2016-02-11T00:01:01','liowci')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 71,'Jeremy Marilli','Hong Kong SAR China','(526) 435-1819','jeremy.marilli@vesa.pf','2019-08-31T05:14:14','vesa')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 72,'Kathryn Huet','Vanuatu','(937) 855-5936','kathryn.huet@wupikdoh.by','2014-01-03T20:52:52','wupikdoh')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 73,'Lelia Matsuo','Timor-Leste','(960) 335-6192','lelia.matsuo@dajsiphaj.az','2014-10-24T10:27:27','dajsiphaj')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 74,'Virginia Woods','Paraguay','(735) 809-2611','virginia.woods@soofpe.ht','2016-10-15T20:51:51','soofpe')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 75,'Sally Aoki','Syria','(857) 797-7918','sally.aoki@aruzusjas.tc','2015-01-03T22:56:56','aruzusjas')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 76,'Isabelle de Ridder','Namibia','(659) 331-1543','isabelle.deridder@ufeco.in','2017-08-02T22:56:56','ufeco')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 77,'Rosie Murphy','North Korea','(759) 639-8597','rosie.murphy@uneehi.id','2017-02-19T12:31:31','uneehi')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 78,'Lou Meyer','United Arab Emirates','(942) 352-4854','lou.meyer@hahinaba.gm','2014-03-18T11:29:29','hahinaba')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 79,'Rodney Love','Bosnia & Herzegovina','(247) 867-8287','rodney.love@zun.ph','2022-07-18T16:40:40','zun')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 80,'Kenneth Bianchini','Costa Rica','(302) 793-9936','kenneth.bianchini@jo.ws','2021-06-10T02:06:06','jo')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 81,'Essie Dietrich','Suriname','(861) 740-6628','essie.dietrich@goltuefo.mn','2015-03-17T14:35:35','goltuefo')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 82,'Leila Simon','U.S. Outlying Islands','(953) 866-9992','leila.simon@lupuwuzo.gw','2014-05-19T01:04:04','lupuwuzo')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 83,'Eva Pierre','Uruguay','(915) 491-8384','eva.pierre@reduzris.ee','2014-01-31T01:04:04','reduzris')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 84,'Landon Moretti','Ireland','(584) 909-6235','landon.moretti@pubsav.sk','2019-05-30T11:29:29','pubsav')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 85,'Mittie Sardi','Libya','(673) 849-4256','mittie.sardi@lullip.nf','2018-08-27T18:45:45','lullip')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 86,'Corey McDaniel','Bosnia & Herzegovina','(268) 208-9643','corey.mcdaniel@aba.tc','2022-07-29T07:19:19','aba')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 87,'Hester Stein','Sudan','(873) 489-6641','hester.stein@kettujwo.eu','2015-04-03T15:38:38','kettujwo')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 88,'Danny Lowe','Bermuda','(243) 974-5539','danny.lowe@ju.sd','2022-09-07T21:52:52','ju')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 89,'Lillie Winter','Slovenia','(816) 699-1291','lillie.winter@vioburez.vi','2015-11-15T19:48:48','vioburez')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 90,'Brandon Borchi','Croatia','(319) 401-1090','brandon.borchi@ig.al','2021-05-09T06:15:15','ig')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 91,'Isaac Bernardi','Cook Islands','(359) 691-6408','isaac.bernardi@omu.bj','2021-07-01T11:29:29','omu')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 92,'Clyde Crawford','Aruba','(273) 892-4646','clyde.crawford@luw.dz','2023-03-14T03:08:08','luw')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 93,'Paul Sherman','Cameroon','(304) 610-2881','paul.sherman@pi.cf','2022-02-22T03:08:08','pi')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 94,'Craig Russell','Antigua & Barbuda','(237) 969-2900','craig.russell@zu.nz','2023-04-30T10:26:26','zu')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 95,'John Sutton','Bhutan','(207) 424-6468','john.sutton@ag.ee','2022-08-24T21:54:54','ag')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 96,'Francisco Formigli','Gambia','(481) 661-8179','francisco.formigli@fopav.tn','2020-05-04T01:04:04','fopav')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 97,'Gary Baker','Algeria','(212) 510-3444','gary.baker@ji.cf','2023-07-19T06:17:17','ji')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 98,'Earl Giovannoni','Grenada','(433) 862-3076','earl.giovannoni@lojet.ge','2020-01-31T15:38:38','lojet')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 99,'Helen Zanieri','Malta','(619) 506-4452','helen.zanieri@ukve.tn','2018-03-21T08:20:20','ukve')
insert into clinic(version, id,name,country,phone,email,created_on,created_by) values (1, 100,'Agnes Toccafondi','Madagascar','(616) 688-6883','agnes.toccafondi@viipo.ae','2018-06-04T02:07:07','viipo')
insert into partner(version, id,name,phone,email) values (1, 1,'Eula Lane','(762) 526-5961','eula.lane@jigrormo.ye')
insert into partner(version, id,name,phone,email) values (1, 2,'Barry Rodriquez','(267) 955-5124','barry.rodriquez@zun.mm')
insert into partner(version, id,name,phone,email) values (1, 3,'Eugenia Selvi','(680) 368-2192','eugenia.selvi@capfad.vn')
insert into partner(version, id,name,phone,email) values (1, 4,'Alejandro Miles','(281) 301-2039','alejandro.miles@dec.bn')
insert into partner(version, id,name,phone,email) values (1, 5,'Cora Tesi','(600) 616-7955','cora.tesi@bivo.yt')
insert into partner(version, id,name,phone,email) values (1, 6,'Marguerite Ishii','(882) 813-1374','marguerite.ishii@judbilo.gn')
insert into partner(version, id,name,phone,email) values (1, 7,'Mildred Jacobs','(642) 665-1763','mildred.jacobs@joraf.wf')
insert into partner(version, id,name,phone,email) values (1, 8,'Gene Goodman','(383) 458-2132','gene.goodman@kem.tl')
insert into partner(version, id,name,phone,email) values (1, 9,'Lettie Bennett','(769) 335-6771','lettie.bennett@odeter.bb')
insert into partner(version, id,name,phone,email) values (1, 10,'Mabel Leach','(803) 586-8035','mabel.leach@lisohuje.vi')
insert into partner(version, id,name,phone,email) values (1, 11,'Jordan Miccinesi','(531) 919-2280','jordan.miccinesi@duod.gy')
insert into partner(version, id,name,phone,email) values (1, 12,'Marie Parkes','(814) 667-8937','marie.parkes@nowufpus.ph')
insert into partner(version, id,name,phone,email) values (1, 13,'Rose Gray','(713) 311-8766','rose.gray@kagu.hr')
insert into partner(version, id,name,phone,email) values (1, 14,'Garrett Stokes','(381) 421-2371','garrett.stokes@fef.bg')
insert into partner(version, id,name,phone,email) values (1, 15,'Barbara Matthieu','(940) 463-7299','barbara.matthieu@derwogi.jm')
insert into partner(version, id,name,phone,email) values (1, 16,'Jean Rhodes','(777) 435-9570','jean.rhodes@wehovuce.gu')
insert into partner(version, id,name,phone,email) values (1, 17,'Jack Romoli','(517) 393-9630','jack.romoli@zamum.bw')
insert into partner(version, id,name,phone,email) values (1, 18,'Pearl Holden','(711) 904-3669','pearl.holden@dunebuh.cr')
insert into partner(version, id,name,phone,email) values (1, 19,'Belle Montero','(935) 404-4792','belle.montero@repiwid.si')
insert into partner(version, id,name,phone,email) values (1, 20,'Olive Molina','(935) 267-8492','olive.molina@razuppa.ga')
insert into partner(version, id,name,phone,email) values (1, 21,'Minerva Todd','(763) 948-4815','minerva.todd@kulmenim.ad')
insert into partner(version, id,name,phone,email) values (1, 22,'Bobby Pearson','(238) 240-2561','bobby.pearson@ib.kg')
insert into partner(version, id,name,phone,email) values (1, 23,'Larry Ciappi','(410) 257-1723','larry.ciappi@ba.lk')
insert into partner(version, id,name,phone,email) values (1, 24,'Ronnie Salucci','(566) 726-3346','ronnie.salucci@tohhij.lv')
insert into partner(version, id,name,phone,email) values (1, 25,'Walter Grossi','(416) 906-7221','walter.grossi@tuvo.sa')
insert into partner(version, id,name,phone,email) values (1, 26,'Frances Koopmans','(611) 712-1562','frances.koopmans@foga.tw')
insert into partner(version, id,name,phone,email) values (1, 27,'Frances Fujimoto','(919) 887-8542','frances.fujimoto@uswuzzub.jp')
insert into partner(version, id,name,phone,email) values (1, 28,'Olivia Vidal','(982) 684-7650','olivia.vidal@hivwerip.vc')
insert into partner(version, id,name,phone,email) values (1, 29,'Edna Henry','(811) 931-8202','edna.henry@gugusu.rw')
insert into partner(version, id,name,phone,email) values (1, 30,'Lydia Brun','(927) 400-3928','lydia.brun@zedekak.md')
insert into partner(version, id,name,phone,email) values (1, 31,'Jay Blake','(365) 345-1498','jay.blake@ral.mk')
insert into partner(version, id,name,phone,email) values (1, 32,'Isabel Serafini','(656) 968-9869','isabel.serafini@turuhu.bh')
insert into partner(version, id,name,phone,email) values (1, 33,'Rebecca Carter','(739) 612-6585','rebecca.carter@omjo.et')
insert into partner(version, id,name,phone,email) values (1, 34,'Maurice Fabbrini','(485) 521-2687','maurice.fabbrini@rig.bh')
insert into partner(version, id,name,phone,email) values (1, 35,'Ollie Turnbull','(835) 620-3330','ollie.turnbull@sicewap.org')
insert into partner(version, id,name,phone,email) values (1, 36,'Jerry Hopkins','(211) 851-5960','jerry.hopkins@fo.mh')
insert into partner(version, id,name,phone,email) values (1, 37,'Nora Lyons','(811) 311-5257','nora.lyons@gegijap.na')
insert into partner(version, id,name,phone,email) values (1, 38,'Anne Weiß','(843) 836-3759','anne.weiß@kuvesa.pe')
insert into partner(version, id,name,phone,email) values (1, 39,'Louise Gauthier','(913) 235-1856','louise.gauthier@lapahu.mt')
insert into partner(version, id,name,phone,email) values (1, 40,'Lloyd Fani','(467) 487-7239','lloyd.fani@zev.ru')
insert into partner(version, id,name,phone,email) values (1, 41,'Maud Dunn','(724) 340-3634','maud.dunn@nabeaga.ni')
insert into partner(version, id,name,phone,email) values (1, 42,'Henry Gigli','(413) 229-8428','henry.gigli@kaot.ps')
insert into partner(version, id,name,phone,email) values (1, 43,'Virgie Werner','(886) 292-9749','virgie.werner@tawuctuj.cf')
insert into partner(version, id,name,phone,email) values (1, 44,'Gregory Cozzi','(418) 472-1239','gregory.cozzi@eh.ru')
insert into partner(version, id,name,phone,email) values (1, 45,'Lucinda Gil','(961) 233-3461','lucinda.gil@fajjusuz.kr')
insert into partner(version, id,name,phone,email) values (1, 46,'Gertrude Verbeek','(605) 226-4037','gertrude.verbeek@pave.cc')
insert into partner(version, id,name,phone,email) values (1, 47,'Mattie Graham','(719) 765-1705','mattie.graham@ispaviw.gt')
insert into partner(version, id,name,phone,email) values (1, 48,'Bryan Shaw','(232) 228-5539','bryan.shaw@ha.ee')
insert into partner(version, id,name,phone,email) values (1, 49,'Essie Adams','(768) 554-8377','essie.adams@iliat.cw')
insert into partner(version, id,name,phone,email) values (1, 50,'Gary Osborne','(311) 731-7079','gary.osborne@do.ga')
insert into partner(version, id,name,phone,email) values (1, 51,'Richard Silva','(207) 554-6244','richard.silva@wi.lc')
insert into partner(version, id,name,phone,email) values (1, 52,'Dustin Pestelli','(558) 913-2855','dustin.pestelli@iwage.la')
insert into partner(version, id,name,phone,email) values (1, 53,'Henrietta Hilton','(832) 759-6654','henrietta.hilton@joopoju.pn')
insert into partner(version, id,name,phone,email) values (1, 54,'Francisco Giordano','(482) 736-8079','francisco.giordano@gojawu.tn')
insert into partner(version, id,name,phone,email) values (1, 55,'Cynthia Sardi','(677) 345-2680','cynthia.sardi@afigoh.mm')
insert into partner(version, id,name,phone,email) values (1, 56,'Lula Testi','(610) 374-7581','lula.testi@benom.tj')
insert into partner(version, id,name,phone,email) values (1, 57,'Bess Lucas','(982) 583-8067','bess.lucas@jevakbe.cd')
insert into partner(version, id,name,phone,email) values (1, 58,'Linnie Driessen','(680) 266-3167','linnie.driessen@darhow.tr')
insert into partner(version, id,name,phone,email) values (1, 59,'Eva Tesi','(611) 955-4652','eva.tesi@dupid.cf')
insert into partner(version, id,name,phone,email) values (1, 60,'Augusta Sakai','(940) 714-8088','augusta.sakai@comouc.ee')
insert into partner(version, id,name,phone,email) values (1, 61,'Mathilda Schwarz','(868) 481-5125','mathilda.schwarz@igunisi.ao')
insert into partner(version, id,name,phone,email) values (1, 62,'Joe Riley','(225) 395-2772','joe.riley@pe.vu')
insert into partner(version, id,name,phone,email) values (1, 63,'Leon McGee','(365) 837-6888','leon.mcgee@puk.se')
insert into partner(version, id,name,phone,email) values (1, 64,'Florence Viviani','(606) 352-8734','florence.viviani@vegub.no')
insert into partner(version, id,name,phone,email) values (1, 65,'Lee Miceli','(555) 800-7339','lee.miceli@rucwi.pf')
insert into partner(version, id,name,phone,email) values (1, 66,'Celia Sodi','(657) 357-3671','celia.sodi@agijit.iq')
insert into partner(version, id,name,phone,email) values (1, 67,'Aaron Misuri','(523) 789-5485','aaron.misuri@loolu.lu')
insert into partner(version, id,name,phone,email) values (1, 68,'Fanny Parkinson','(766) 966-7387','fanny.parkinson@tupwovali.cw')
insert into partner(version, id,name,phone,email) values (1, 69,'Phoebe Vitale','(672) 613-2954','phoebe.vitale@hidge.fo')
insert into partner(version, id,name,phone,email) values (1, 70,'Edith Brennan','(803) 549-9387','edith.brennan@liowci.ir')
insert into partner(version, id,name,phone,email) values (1, 71,'Jeremy Marilli','(526) 435-1819','jeremy.marilli@vesa.pf')
insert into partner(version, id,name,phone,email) values (1, 72,'Kathryn Huet','(937) 855-5936','kathryn.huet@wupikdoh.by')
insert into partner(version, id,name,phone,email) values (1, 73,'Lelia Matsuo','(960) 335-6192','lelia.matsuo@dajsiphaj.az')
insert into partner(version, id,name,phone,email) values (1, 74,'Virginia Woods','(735) 809-2611','virginia.woods@soofpe.ht')
insert into partner(version, id,name,phone,email) values (1, 75,'Sally Aoki','(857) 797-7918','sally.aoki@aruzusjas.tc')
insert into partner(version, id,name,phone,email) values (1, 76,'Isabelle de Ridder','(659) 331-1543','isabelle.deridder@ufeco.in')
insert into partner(version, id,name,phone,email) values (1, 77,'Rosie Murphy','(759) 639-8597','rosie.murphy@uneehi.id')
insert into partner(version, id,name,phone,email) values (1, 78,'Lou Meyer','(942) 352-4854','lou.meyer@hahinaba.gm')
insert into partner(version, id,name,phone,email) values (1, 79,'Rodney Love','(247) 867-8287','rodney.love@zun.ph')
insert into partner(version, id,name,phone,email) values (1, 80,'Kenneth Bianchini','(302) 793-9936','kenneth.bianchini@jo.ws')
insert into partner(version, id,name,phone,email) values (1, 81,'Essie Dietrich','(861) 740-6628','essie.dietrich@goltuefo.mn')
insert into partner(version, id,name,phone,email) values (1, 82,'Leila Simon','(953) 866-9992','leila.simon@lupuwuzo.gw')
insert into partner(version, id,name,phone,email) values (1, 83,'Eva Pierre','(915) 491-8384','eva.pierre@reduzris.ee')
insert into partner(version, id,name,phone,email) values (1, 84,'Landon Moretti','(584) 909-6235','landon.moretti@pubsav.sk')
insert into partner(version, id,name,phone,email) values (1, 85,'Mittie Sardi','(673) 849-4256','mittie.sardi@lullip.nf')
insert into partner(version, id,name,phone,email) values (1, 86,'Corey McDaniel','(268) 208-9643','corey.mcdaniel@aba.tc')
insert into partner(version, id,name,phone,email) values (1, 87,'Hester Stein','(873) 489-6641','hester.stein@kettujwo.eu')
insert into partner(version, id,name,phone,email) values (1, 88,'Danny Lowe','(243) 974-5539','danny.lowe@ju.sd')
insert into partner(version, id,name,phone,email) values (1, 89,'Lillie Winter','(816) 699-1291','lillie.winter@vioburez.vi')
insert into partner(version, id,name,phone,email) values (1, 90,'Brandon Borchi','(319) 401-1090','brandon.borchi@ig.al')
insert into partner(version, id,name,phone,email) values (1, 91,'Isaac Bernardi','(359) 691-6408','isaac.bernardi@omu.bj')
insert into partner(version, id,name,phone,email) values (1, 92,'Clyde Crawford','(273) 892-4646','clyde.crawford@luw.dz')
insert into partner(version, id,name,phone,email) values (1, 93,'Paul Sherman','(304) 610-2881','paul.sherman@pi.cf')
insert into partner(version, id,name,phone,email) values (1, 94,'Craig Russell','(237) 969-2900','craig.russell@zu.nz')
insert into partner(version, id,name,phone,email) values (1, 95,'John Sutton','(207) 424-6468','john.sutton@ag.ee')
insert into partner(version, id,name,phone,email) values (1, 96,'Francisco Formigli','(481) 661-8179','francisco.formigli@fopav.tn')
insert into partner(version, id,name,phone,email) values (1, 97,'Gary Baker','(212) 510-3444','gary.baker@ji.cf')
insert into partner(version, id,name,phone,email) values (1, 98,'Earl Giovannoni','(433) 862-3076','earl.giovannoni@lojet.ge')
insert into partner(version, id,name,phone,email) values (1, 99,'Helen Zanieri','(619) 506-4452','helen.zanieri@ukve.tn')
insert into partner(version, id,name,phone,email) values (1, 100,'Agnes Toccafondi','(616) 688-6883','agnes.toccafondi@viipo.ae')
insert into house(version, id,address,capacity,manager) values (1, 1,'1395 Jigror Park','70','jigrormo')
insert into house(version, id,address,capacity,manager) values (1, 2,'216 Zunnij Grove','11','zun')
insert into house(version, id,address,capacity,manager) values (1, 3,'1016 Capfad View','51','capfad')
insert into house(version, id,address,capacity,manager) values (1, 4,'214 Decde River','11','dec')
insert into house(version, id,address,capacity,manager) values (1, 5,'1050 Bivo Way','53','bivo')
insert into house(version, id,address,capacity,manager) values (1, 6,'1734 Judbi Grove','87','judbilo')
insert into house(version, id,address,capacity,manager) values (1, 7,'1143 Joraf Way','58','joraf')
insert into house(version, id,address,capacity,manager) values (1, 8,'287 Kemdol Street','15','kem')
insert into house(version, id,address,capacity,manager) values (1, 9,'1302 Odeter Circle','66','odeter')
insert into house(version, id,address,capacity,manager) values (1, 10,'1563 Lisoh Square','79','lisohuje')
insert into house(version, id,address,capacity,manager) values (1, 11,'842 Duod Lane','42','duod')
insert into house(version, id,address,capacity,manager) values (1, 12,'1624 Nowuf Plaza','82','nowufpus')
insert into house(version, id,address,capacity,manager) values (1, 13,'1325 Kagu Loop','67','kagu')
insert into house(version, id,address,capacity,manager) values (1, 14,'310 Feffo Grove','16','fef')
insert into house(version, id,address,capacity,manager) values (1, 15,'1888 Derwo Park','95','derwogi')
insert into house(version, id,address,capacity,manager) values (1, 16,'1500 Wehovu Boulevard','75','wehovuce')
insert into house(version, id,address,capacity,manager) values (1, 17,'984 Zamum Drive','50','zamum')
insert into house(version, id,address,capacity,manager) values (1, 18,'1497 Dune Parkway','75','dunebuh')
insert into house(version, id,address,capacity,manager) values (1, 19,'1836 Repi Terrace','92','repiwid')
insert into house(version, id,address,capacity,manager) values (1, 20,'1805 Razup Extension','91','razuppa')
insert into house(version, id,address,capacity,manager) values (1, 21,'1477 Kulmen Junction','74','kulmenim')
insert into house(version, id,address,capacity,manager) values (1, 22,'191 Ibca View','10','ib')
insert into house(version, id,address,capacity,manager) values (1, 23,'569 Baaci Place','29','ba')
insert into house(version, id,address,capacity,manager) values (1, 24,'999 Tohhij Pass','50','tohhij')
insert into house(version, id,address,capacity,manager) values (1, 25,'736 Tuvo Road','37','tuvo')
insert into house(version, id,address,capacity,manager) values (1, 26,'1153 Foga Turnpike','58','foga')
insert into house(version, id,address,capacity,manager) values (1, 27,'1764 Uswuz Trail','89','uswuzzub')
insert into house(version, id,address,capacity,manager) values (1, 28,'1818 Hivwe Point','91','hivwerip')
insert into house(version, id,address,capacity,manager) values (1, 29,'1541 Gugu Heights','77','gugusu')
insert into house(version, id,address,capacity,manager) values (1, 30,'1898 Zede Point','95','zedekak')
insert into house(version, id,address,capacity,manager) values (1, 31,'299 Ralcul Place','15','ral')
insert into house(version, id,address,capacity,manager) values (1, 32,'1018 Turuhu Court','51','turuhu')
insert into house(version, id,address,capacity,manager) values (1, 33,'1307 Omjo Highway','66','omjo')
insert into house(version, id,address,capacity,manager) values (1, 34,'630 Riggi Park','32','rig')
insert into house(version, id,address,capacity,manager) values (1, 35,'1596 Sice Trail','80','sicewap')
insert into house(version, id,address,capacity,manager) values (1, 36,'197 Fodin River','10','fo')
insert into house(version, id,address,capacity,manager) values (1, 37,'1579 Gegi Square','79','gegijap')
insert into house(version, id,address,capacity,manager) values (1, 38,'1668 Kuve Park','84','kuvesa')
insert into house(version, id,address,capacity,manager) values (1, 39,'1882 Lapa Boulevard','95','lapahu')
insert into house(version, id,address,capacity,manager) values (1, 40,'645 Zevvat Pass','33','zev')
insert into house(version, id,address,capacity,manager) values (1, 41,'1380 Nabe Terrace','69','nabeaga')
insert into house(version, id,address,capacity,manager) values (1, 42,'717 Kaot Ridge','36','kaot')
insert into house(version, id,address,capacity,manager) values (1, 43,'1654 Tawuc View','83','tawuctuj')
insert into house(version, id,address,capacity,manager) values (1, 44,'599 Ehgad Road','30','eh')
insert into house(version, id,address,capacity,manager) values (1, 45,'1798 Fajju View','90','fajjusuz')
insert into house(version, id,address,capacity,manager) values (1, 46,'1198 Pave Extension','60','pave')
insert into house(version, id,address,capacity,manager) values (1, 47,'1341 Ispav Mill','67','ispaviw')
insert into house(version, id,address,capacity,manager) values (1, 48,'110 Haam Grove','6','ha')
insert into house(version, id,address,capacity,manager) values (1, 49,'1317 Iliat Glen','66','iliat')
insert into house(version, id,address,capacity,manager) values (1, 50,'303 Dogo Road','15','do')
insert into house(version, id,address,capacity,manager) values (1, 51,'191 Wipir Pike','10','wi')
insert into house(version, id,address,capacity,manager) values (1, 52,'923 Iwage Parkway','47','iwage')
insert into house(version, id,address,capacity,manager) values (1, 53,'1605 Joopo Avenue','81','joopoju')
insert into house(version, id,address,capacity,manager) values (1, 54,'718 Gojawu Trail','36','gojawu')
insert into house(version, id,address,capacity,manager) values (1, 55,'1008 Afigoh Path','51','afigoh')
insert into house(version, id,address,capacity,manager) values (1, 56,'1052 Benom Terrace','53','benom')
insert into house(version, id,address,capacity,manager) values (1, 57,'1902 Jevak Lane','96','jevakbe')
insert into house(version, id,address,capacity,manager) values (1, 58,'1128 Darhow Trail','57','darhow')
insert into house(version, id,address,capacity,manager) values (1, 59,'1050 Dupid Extension','53','dupid')
insert into house(version, id,address,capacity,manager) values (1, 60,'1754 Como Manor','88','comouc')
insert into house(version, id,address,capacity,manager) values (1, 61,'1648 Iguni Drive','83','igunisi')
insert into house(version, id,address,capacity,manager) values (1, 62,'141 Pepal Lane','7','pe')
insert into house(version, id,address,capacity,manager) values (1, 63,'265 Pukvoh Point','14','puk')
insert into house(version, id,address,capacity,manager) values (1, 64,'1088 Vegub Plaza','55','vegub')
insert into house(version, id,address,capacity,manager) values (1, 65,'843 Rucwi Point','43','rucwi')
insert into house(version, id,address,capacity,manager) values (1, 66,'1026 Agijit Manor','52','agijit')
insert into house(version, id,address,capacity,manager) values (1, 67,'848 Loolu Pass','43','loolu')
insert into house(version, id,address,capacity,manager) values (1, 68,'1492 Tupwov Path','75','tupwovali')
insert into house(version, id,address,capacity,manager) values (1, 69,'1086 Hidge Highway','55','hidge')
insert into house(version, id,address,capacity,manager) values (1, 70,'1516 Liow Boulevard','76','liowci')
insert into house(version, id,address,capacity,manager) values (1, 71,'807 Vesa Point','41','vesa')
insert into house(version, id,address,capacity,manager) values (1, 72,'1936 Wupik Plaza','97','wupikdoh')
insert into house(version, id,address,capacity,manager) values (1, 73,'1776 Dajsip Terrace','89','dajsiphaj')
insert into house(version, id,address,capacity,manager) values (1, 74,'1381 Soof Avenue','69','soofpe')
insert into house(version, id,address,capacity,manager) values (1, 75,'1737 Aruzus Plaza','87','aruzusjas')
insert into house(version, id,address,capacity,manager) values (1, 76,'1222 Ufeco Manor','61','ufeco')
insert into house(version, id,address,capacity,manager) values (1, 77,'1311 Uneehi Loop','66','uneehi')
insert into house(version, id,address,capacity,manager) values (1, 78,'1896 Hahin River','95','hahinaba')
insert into house(version, id,address,capacity,manager) values (1, 79,'232 Zunago Street','12','zun')
insert into house(version, id,address,capacity,manager) values (1, 80,'452 Joluk Way','23','jo')
insert into house(version, id,address,capacity,manager) values (1, 81,'1697 Goltu View','85','goltuefo')
insert into house(version, id,address,capacity,manager) values (1, 82,'1862 Lupuwu Junction','94','lupuwuzo')
insert into house(version, id,address,capacity,manager) values (1, 83,'1921 Reduz Turnpike','97','reduzris')
insert into house(version, id,address,capacity,manager) values (1, 84,'857 Pubsav Square','43','pubsav')
insert into house(version, id,address,capacity,manager) values (1, 85,'1008 Lullip Place','51','lullip')
insert into house(version, id,address,capacity,manager) values (1, 86,'226 Abaudu Center','12','aba')
insert into house(version, id,address,capacity,manager) values (1, 87,'1688 Kettuj Loop','85','kettujwo')
insert into house(version, id,address,capacity,manager) values (1, 88,'204 Junib Circle','10','ju')
insert into house(version, id,address,capacity,manager) values (1, 89,'1564 Viobu Way','79','vioburez')
insert into house(version, id,address,capacity,manager) values (1, 90,'469 Igfa Parkway','24','ig')
insert into house(version, id,address,capacity,manager) values (1, 91,'440 Omuse River','22','omu')
insert into house(version, id,address,capacity,manager) values (1, 92,'101 Luwmo Heights','5','luw')
insert into house(version, id,address,capacity,manager) values (1, 93,'312 Pice Ridge','16','pi')
insert into house(version, id,address,capacity,manager) values (1, 94,'76 Zuufa Grove','4','zu')
insert into house(version, id,address,capacity,manager) values (1, 95,'211 Agmo Circle','11','ag')
insert into house(version, id,address,capacity,manager) values (1, 96,'672 Fopav Trail','34','fopav')
insert into house(version, id,address,capacity,manager) values (1, 97,'31 Jibe Ridge','2','ji')
insert into house(version, id,address,capacity,manager) values (1, 98,'723 Lojet Junction','37','lojet')
insert into house(version, id,address,capacity,manager) values (1, 99,'1095 Ukve Trail','55','ukve')
insert into house(version, id,address,capacity,manager) values (1, 100,'1054 Viipo Boulevard','53','viipo')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 1,'Eula','Lane','2016-09-20','jigrormo','jigrormo','jigrormo')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 2,'Barry','Rodriquez','2022-08-15','zun','zun','zun')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 3,'Eugenia','Selvi','2018-08-13','capfad','capfad','capfad')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 4,'Alejandro','Miles','2022-08-19','dec','dec','dec')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 5,'Cora','Tesi','2018-06-12','bivo','bivo','bivo')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 6,'Marguerite','Ishii','2015-01-07','judbilo','judbilo','judbilo')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 7,'Mildred','Jacobs','2017-12-23','joraf','joraf','joraf')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 8,'Gene','Goodman','2022-04-07','kem','kem','kem')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 9,'Lettie','Bennett','2017-03-08','odeter','odeter','odeter')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 10,'Mabel','Leach','2015-11-16','lisohuje','lisohuje','lisohuje')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 11,'Jordan','Miccinesi','2019-06-28','duod','duod','duod')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 12,'Marie','Parkes','2015-07-28','nowufpus','nowufpus','nowufpus')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 13,'Rose','Gray','2017-01-26','kagu','kagu','kagu')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 14,'Garrett','Stokes','2022-02-24','fef','fef','fef')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 15,'Barbara','Matthieu','2014-04-01','derwogi','derwogi','derwogi')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 16,'Jean','Rhodes','2016-03-11','wehovuce','wehovuce','wehovuce')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 17,'Jack','Romoli','2018-10-10','zamum','zamum','zamum')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 18,'Pearl','Holden','2016-03-16','dunebuh','dunebuh','dunebuh')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 19,'Belle','Montero','2014-07-06','repiwid','repiwid','repiwid')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 20,'Olive','Molina','2014-08-31','razuppa','razuppa','razuppa')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 21,'Minerva','Todd','2016-04-22','kulmenim','kulmenim','kulmenim')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 22,'Bobby','Pearson','2022-10-01','ib','ib','ib')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 23,'Larry','Ciappi','2020-11-07','ba','ba','ba')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 24,'Ronnie','Salucci','2018-09-14','tohhij','tohhij','tohhij')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 25,'Walter','Grossi','2020-01-07','tuvo','tuvo','tuvo')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 26,'Frances','Koopmans','2017-12-06','foga','foga','foga')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 27,'Frances','Fujimoto','2014-11-15','uswuzzub','uswuzzub','uswuzzub')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 28,'Olivia','Vidal','2014-08-07','hivwerip','hivwerip','hivwerip')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 29,'Edna','Henry','2015-12-27','gugusu','gugusu','gugusu')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 30,'Lydia','Brun','2014-03-14','zedekak','zedekak','zedekak')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 31,'Jay','Blake','2022-03-16','ral','ral','ral')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 32,'Isabel','Serafini','2018-08-10','turuhu','turuhu','turuhu')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 33,'Rebecca','Carter','2017-02-28','omjo','omjo','omjo')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 34,'Maurice','Fabbrini','2020-07-18','rig','rig','rig')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 35,'Ollie','Turnbull','2015-09-17','sicewap','sicewap','sicewap')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 36,'Jerry','Hopkins','2022-09-20','fo','fo','fo')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 37,'Nora','Lyons','2015-10-18','gegijap','gegijap','gegijap')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 38,'Anne','Weiß','2015-05-09','kuvesa','kuvesa','kuvesa')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 39,'Louise','Gauthier','2014-04-12','lapahu','lapahu','lapahu')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 40,'Lloyd','Fani','2020-06-22','zev','zev','zev')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 41,'Maud','Dunn','2016-10-17','nabeaga','nabeaga','nabeaga')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 42,'Henry','Gigli','2020-02-11','kaot','kaot','kaot')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 43,'Virgie','Werner','2015-06-04','tawuctuj','tawuctuj','tawuctuj')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 44,'Gregory','Cozzi','2020-09-14','eh','eh','eh')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 45,'Lucinda','Gil','2014-09-14','fajjusuz','fajjusuz','fajjusuz')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 46,'Gertrude','Verbeek','2017-09-15','pave','pave','pave')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 47,'Mattie','Graham','2016-12-27','ispaviw','ispaviw','ispaviw')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 48,'Bryan','Shaw','2023-02-26','ha','ha','ha')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 49,'Essie','Adams','2017-02-08','iliat','iliat','iliat')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 50,'Gary','Osborne','2022-03-10','do','do','do')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 51,'Richard','Silva','2022-10-01','wi','wi','wi')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 52,'Dustin','Pestelli','2019-01-31','iwage','iwage','iwage')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 53,'Henrietta','Hilton','2015-08-31','joopoju','joopoju','joopoju')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 54,'Francisco','Giordano','2020-02-09','gojawu','gojawu','gojawu')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 55,'Cynthia','Sardi','2018-08-28','afigoh','afigoh','afigoh')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 56,'Lula','Testi','2018-06-09','benom','benom','benom')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 57,'Bess','Lucas','2014-03-07','jevakbe','jevakbe','jevakbe')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 58,'Linnie','Driessen','2018-01-21','darhow','darhow','darhow')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 59,'Eva','Tesi','2018-06-11','dupid','dupid','dupid')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 60,'Augusta','Sakai','2014-12-02','comouc','comouc','comouc')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 61,'Mathilda','Schwarz','2015-06-14','igunisi','igunisi','igunisi')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 62,'Joe','Riley','2022-12-31','pe','pe','pe')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 63,'Leon','McGee','2022-05-18','puk','puk','puk')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 64,'Florence','Viviani','2018-04-04','vegub','vegub','vegub')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 65,'Lee','Miceli','2019-06-26','rucwi','rucwi','rucwi')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 66,'Celia','Sodi','2018-07-25','agijit','agijit','agijit')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 67,'Aaron','Misuri','2019-06-16','loolu','loolu','loolu')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 68,'Fanny','Parkinson','2016-03-26','tupwovali','tupwovali','tupwovali')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 69,'Phoebe','Vitale','2018-04-08','hidge','hidge','hidge')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 70,'Edith','Brennan','2016-02-11','liowci','liowci','liowci')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 71,'Jeremy','Marilli','2019-08-31','vesa','vesa','vesa')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 72,'Kathryn','Huet','2014-01-03','wupikdoh','wupikdoh','wupikdoh')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 73,'Lelia','Matsuo','2014-10-24','dajsiphaj','dajsiphaj','dajsiphaj')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 74,'Virginia','Woods','2016-10-15','soofpe','soofpe','soofpe')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 75,'Sally','Aoki','2015-01-03','aruzusjas','aruzusjas','aruzusjas')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 76,'Isabelle','de Ridder','2017-08-02','ufeco','ufeco','ufeco')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 77,'Rosie','Murphy','2017-02-19','uneehi','uneehi','uneehi')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 78,'Lou','Meyer','2014-03-18','hahinaba','hahinaba','hahinaba')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 79,'Rodney','Love','2022-07-18','zun','zun','zun')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 80,'Kenneth','Bianchini','2021-06-10','jo','jo','jo')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 81,'Essie','Dietrich','2015-03-17','goltuefo','goltuefo','goltuefo')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 82,'Leila','Simon','2014-05-19','lupuwuzo','lupuwuzo','lupuwuzo')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 83,'Eva','Pierre','2014-01-31','reduzris','reduzris','reduzris')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 84,'Landon','Moretti','2019-05-30','pubsav','pubsav','pubsav')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 85,'Mittie','Sardi','2018-08-27','lullip','lullip','lullip')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 86,'Corey','McDaniel','2022-07-29','aba','aba','aba')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 87,'Hester','Stein','2015-04-03','kettujwo','kettujwo','kettujwo')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 88,'Danny','Lowe','2022-09-07','ju','ju','ju')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 89,'Lillie','Winter','2015-11-15','vioburez','vioburez','vioburez')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 90,'Brandon','Borchi','2021-05-09','ig','ig','ig')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 91,'Isaac','Bernardi','2021-07-01','omu','omu','omu')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 92,'Clyde','Crawford','2023-03-14','luw','luw','luw')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 93,'Paul','Sherman','2022-02-22','pi','pi','pi')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 94,'Craig','Russell','2023-04-30','zu','zu','zu')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 95,'John','Sutton','2022-08-24','ag','ag','ag')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 96,'Francisco','Formigli','2020-05-04','fopav','fopav','fopav')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 97,'Gary','Baker','2023-07-19','ji','ji','ji')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 98,'Earl','Giovannoni','2020-01-31','lojet','lojet','lojet')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 99,'Helen','Zanieri','2018-03-21','ukve','ukve','ukve')
insert into client(version, id,first_name,last_name,dob,access_number,status,house) values (1, 100,'Agnes','Toccafondi','2018-06-04','viipo','viipo','viipo')
